name: Build Only

on: workflow_dispatch

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          
      - name: Build APK
        working-directory: ./crime_search_app
        run: |
          flutter pub get
          flutter build apk --release
          
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: crime_search_app/build/app/outputs/flutter-apk/app-release.apk